# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrant support in PHPStorm http://blog.jetbrains.com/phpstorm/2013/08/vagrant-support-in-phpstorm/

require "rbconfig"

IS_WINDOWS = (RbConfig::CONFIG["host_os"] =~ /mswin|mingw|cygwin/) ? true : false

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # TODO перенести в рецепты, чтобы можно было json отдельно запускать
  appsConf = JSON.parse(File.read("chef.json"))
  appsConf[:run_list] = appsConf.delete("recipes")

  config.vm.box = "bubuntu"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  # fedora with chef
  #config.vm.box_url = "http://static.stasiak.at/fedora-18-x86-2.box"

  # FIXME few sites?
  config.vm.hostname = appsConf["app"]["server"]

  # unfortunely dont work with secured /system32/drivers/etc/hosts
  # vagrant plugin install vagrant-hostsupdater
  # config.hostsupdater.aliases = ["www." + appsConf["app"]["server"], "*.vagrant"]

  config.vm.define :texas do |texas|
      texas.vm.network :public_network
      #texas.vm.network :private_network, ip: "192.168.3.45"
      # texas.vm.network :public_network

      # apache
      # TODO ports from json
      texas.vm.network :forwarded_port, guest: 8010, host: 8010
      texas.vm.network :forwarded_port, guest: 443, host: 444

      texas.vm.network :forwarded_port, guest: 8015, host: 8015

      texas.vm.network :forwarded_port, guest: 3306, host: 3306

      # xdebug
      texas.vm.network :forwarded_port, guest: 9002, host: 9002
  end

  config.vm.synced_folder "apps", "/home/vagrant/www", :nfs => !IS_WINDOWS

  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    # vb.gui = true

    # Use VBoxManage to customize the VM
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ".cookbooks"
    chef.provisioning_path = "/tmp/vagrant-chef"
    # chef.roles_path = ".sandbox/roles"
    # chef.data_bags_path = ".sandbox/data_bags"

    chef.json.merge!(appsConf)

    chef.add_recipe appsConf["app"]["recipe"]

    # chef.add_role "web"
  end
  
end
