name "symfony_lamp"

depends "apt"
depends "dpkg_autostart"
depends "cron"
depends "apache2"
depends "build-essential"
depends "chef_handler"
depends "mysql"
depends "networking_basic"
depends "git"
depends "openssl"
depends "windows"
depends "xdebug"
depends "xml"